### ISSUE TITLE
Make a mechanism to have some columns derive their values from others

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/sqlsynthgen#4]
For instance one of the Star tables has columns `date_of_birth` and `datetime_of_birth`, where one is a coarser version of the other (normalisation?).

**Comment by myyong** [comment]
We had a discussion about how column values can be derived from other values. Examples are 

1. Within tables (e.g. visit end date as subsequent value to visit start date)
1. Between tables (e.g. a lab visit falls between visit start date and end date)

Options [1,2](https://github.com/alan-turing-institute/sqlsynthgen/issues/11#issuecomment-1405124557) addresses these examples in turn.

We agree that it is a good option to pick one of these options and to then customise the software to UCLH needs, so that we can begin the task of privacy evaluation. Creation of a generic solution is not the goal of our project.
